GROUPS = [
    {"id": "DIMMER", "nameZh": "调光", "color": "#f5b800"},
    {"id": "POSITION", "nameZh": "位置", "color": "#f5b800"},
    {"id": "GOBO", "nameZh": "图案", "color": "#9d7bff"},
    {"id": "COLOR", "nameZh": "颜色", "color": "#4d8dff"},
    {"id": "BEAM", "nameZh": "光束", "color": "#42c6a5"},
    {"id": "FOCUS", "nameZh": "聚焦", "color": "#42c6a5"},
    {"id": "CONTROL", "nameZh": "控制", "color": "#ef6b72"},
]

def attr(ma2, group, zh, ue=None, keywords=""):
    return {"id": ma2, "ma2Attribute": ma2, "maFeature": group,
            "preset": group, "gdtfAttribute": ma2, "ueAttribute": ue or ma2,
            "nameZh": zh, "keywords": keywords}

ATTRIBUTES = [
    attr("DIM", "DIMMER", "调光", "Dimmer", "强度 亮度 intensity dimmer"),
    attr("PAN", "POSITION", "水平旋转", "Pan", "pan 水平"),
    attr("TILT", "POSITION", "垂直旋转", "Tilt", "tilt 垂直"),
    attr("POSMODE", "POSITION", "位置模式", "PosMode"),
    attr("GOBO1", "GOBO", "图案轮1", "Gobo", "gobo pattern"),
    attr("GOBO1ROT", "GOBO", "图案旋转", "Gobo Spin"),
    attr("COLOR1", "COLOR", "颜色轮1", "Color"),
    attr("COLORRGB1", "COLOR", "红色", "Red", "red r"),
    attr("COLORRGB2", "COLOR", "绿色", "Green", "green g"),
    attr("COLORRGB3", "COLOR", "蓝色", "Blue", "blue b"),
    attr("COLORRGB4", "COLOR", "青色", "Cyan"),
    attr("COLORRGB5", "COLOR", "白色", "White", "white w"),
    attr("COLORRGB6", "COLOR", "琥珀色", "Amber", "amber a"),
    attr("SHUTTER", "BEAM", "频闪/快门", "Shutter", "strobe shutter"),
    attr("ZOOM", "BEAM", "变焦", "Zoom"),
    attr("FROST", "BEAM", "雾化", "Frost"),
    attr("IRIS", "BEAM", "光圈", "Iris"),
    attr("FOCUS", "FOCUS", "聚焦", "Focus"),
    attr("RESET", "CONTROL", "复位", "Reset"),
    attr("EFFECTWHEEL", "CONTROL", "效果轮", "Effects"),
    attr("EFFECTRATE", "CONTROL", "效果速度", "Effect Rate"),
    attr("PRISM", "BEAM", "棱镜", "Prism"),
    attr("CTC", "COLOR", "色温校正", "CTC"),
    attr("TINT", "COLOR", "色调", "Tint"),
    attr("COLOR_XF", "COLOR", "颜色交叉淡化", "Color XF"),
    attr("HSB_HUE", "COLOR", "HSB色相", "HSB_Hue"),
    attr("HSB_SATURATION", "COLOR", "HSB饱和度", "HSB_Saturation"),
    attr("HSB_BRIGHTNESS", "DIMMER", "HSB亮度", "HSB_Brightness"),
    attr("CIE_X", "COLOR", "CIE X", "CIE_X"),
    attr("CIE_Y", "COLOR", "CIE Y", "CIE_Y"),
    attr("FANMODE", "CONTROL", "风扇模式", "FanMode"),
    attr("SHAPERROT", "BEAM", "切割器旋转", "Shaper Rotation"),
    attr("COLORROT", "COLOR", "颜色轮旋转", "Color Rotation"),
    attr("GOBO1WHEELROT", "GOBO", "图案轮旋转", "Gobo Wheel Rotate"),
    attr("MODESTARTSTOP", "CONTROL", "模式启停", "ModeStartStop"),
    attr("PATTERN", "GOBO", "激光图案", "Pattern"),
    attr("TRANSITIONSPEED", "CONTROL", "图案过渡速度", "Transition Speed"),
    attr("LOOP", "CONTROL", "循环", "Loop"),
    attr("SPEED", "CONTROL", "速度", "Speed"),
    attr("BEAMFLICKER", "BEAM", "光束闪烁", "Beam Flicker"),
    attr("BEAMTHICKNESS", "BEAM", "光束粗细", "Beam Thickness"),
    attr("NUMBEAMS", "BEAM", "光束数量", "NumBeams"),
    attr("ANGLE", "BEAM", "角度", "Angle"),
    attr("VELOCITY", "CONTROL", "速度", "Velocity"),
    attr("LAUNCH", "CONTROL", "发射", "Launch"),
    attr("BURST", "CONTROL", "爆发", "Burst"),
    attr("FOGMIX", "CONTROL", "烟雾混合", "Fog Mix"),
    attr("FOGFLICKER", "CONTROL", "烟雾闪烁", "Fog Flicker"),
    attr("FOGADIVIDE", "CONTROL", "烟雾A分割", "Fog A Divide"),
    attr("FOGASPEEDX", "CONTROL", "烟雾A速度X", "Fog A Speed X"),
    attr("FOGASPEEDY", "CONTROL", "烟雾A速度Y", "Fog A Speed Y"),
    attr("FOGBDIVIDE", "CONTROL", "烟雾B分割", "Fog B Divide"),
    attr("FOGBSPEEDX", "CONTROL", "烟雾B速度X", "Fog B Speed X"),
    attr("FOGBSPEEDY", "CONTROL", "烟雾B速度Y", "Fog B Speed Y"),
]
