export type Resolution=8|16|24|32;
export interface AttributeDef{id:string;ma2Attribute:string;maFeature:string;preset:string;gdtfAttribute:string;ueAttribute:string;nameZh:string;keywords:string;custom?:boolean}
export interface AttributeGroup{id:string;nameZh:string;color:string}
export interface ChannelFunction{id:string;name:string;dmxFrom:number;dmxTo:number;physicalFrom:number;physicalTo:number;attribute:string}
export interface DmxChannel{id:string;address:number;attribute:string;group:string;name:string;resolution:Resolution;byteOrder:'MSB'|'LSB';defaultValue:number;highlightValue:number;physicalFrom:number;physicalTo:number;unit:string;inverted:boolean;ueAttribute:string;functions:ChannelFunction[]}
export interface FixtureMode{id:string;name:string;channels:DmxChannel[]}
export interface FixtureDocument{id:string;schemaVersion:string;revision:number;name:string;shortName:string;manufacturer:{id:string;name:string;shortName:string};category:string;version:string;notes:string;modes:FixtureMode[];wheels:unknown[]}
export interface Preset{id:string;name:string;kind:'channel'|'mode'|'fixture';manufacturer:string;tags:string[];description:string;version:string;payload:Record<string,unknown>}
export interface Catalog{version:string;groups:AttributeGroup[];attributes:AttributeDef[]}
export interface MvrImportOption{key:string;index:number;name:string;manufacturer:string;modes:string[];footprint:number}
export interface MvrItem{id:string;fixtureId:string;fid:number;modeName:string;universe:number;address:number;color:string;name:string}
export interface Ma2Device{ip:string;hostname?:string;remotePort:number;webPort?:number|null;detectedBy:string[];isLocal:boolean}
export type Ma2ImportMode='selected'|'all'|'overwrite';
export interface PushPayload{sceneName:string;items:MvrItem[];ma2Ip:string;ma2Port:number;username?:string;password?:string;options?:{importFixtureTypes?:boolean;patchFixtures?:boolean;testOnly?:boolean;mode?:Ma2ImportMode}}
export interface PushResult{success:boolean;sent:number;errors:string[];warnings?:string[];files?:string[];tempPath?:string|null;commands?:string[];feedback?:{command:string;feedback:string}[]}
